# -*- coding: utf-8 -*-
"""AvaliaçãoFAP-Softex2024_HugoGomes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0oxCZ62u3Nhnk76YetSTCBZWaO820fE
"""

# CRUD - Create, Read, Update, Delete


#  Descrição do Sistema:
#  Vocês foram contratados para desenvolver um sistema básico de gerenciamento de
#  contas bancárias em Python, operado por um único gerente. Este sistema deve incluir as
#  seguintes funcionalidades:

# --------------------------------------------------------------------------------------------------
# - Create

#  Cadastro de Correntistas e Contas Bancárias:
#  o Permitir ao gerente cadastrar novas contas bancárias com os seguintes
#  dados:
#  ▪ Nome do correntista.
#  ▪ Número da conta (único).
#  ▪ Data de abertura da conta.
#  ▪ Tipo da conta (poupança ou corrente).

# - Update;
#  Operações Financeiras:
#  o Depósito: Realizar depósitos em contas cadastradas, registrando cada
#  operação em uma lista de movimentações.
#  o Saque: Realizar saques, com verificação de saldo, e registro na lista de
#  movimentações.

# - Update; Delete;
#  Gerenciamento de Contas:
#  o Edição de Conta: Editar os dados de uma conta existente.
#  o Exclusão de Conta: Remover uma conta bancária do sistema.

# - Read;
#  Extrato Bancário:
#  o Visualizar o extrato bancário de uma conta, exibindo todas as
#  movimentações registradas.

z